# This file should contain all the record creation needed to seed the database with its default values.
# The data can then be loaded with the bin/rails db:seed command (or created alongside the database with db:setup).
#
# Examples:
#
#   movies = Movie.create([{ name: "Star Wars" }, { name: "Lord of the Rings" }])
#   Character.create(name: "Luke", movie: movies.first)

user1 = User.create!(username: "rega1237")
user2 = User.create!(username: "johndoe")
user3 = User.create!(username: "janedoe")
user4 = User.create!(username: "amaury")
user5 = User.create!(username: "aturo")
user6 = User.create!(username: "dangelo")

stadium1 = Stadium.create!(name: "Camp Nou", country: "Spain", seats: 5, photo: "https://i0.wp.com/footballpink.net/wp-content/uploads/2018/02/camp-nou-1.jpg?fit=1024%2C592&ssl=1")
stadium2 = Stadium.create!(name: "Allianz Arena", country: "Germany", seats: 5, photo: "https://imgresizer.eurosport.com/unsafe/1200x0/filters:format(jpeg):focal(1265x679:1267x677)/origin-imgresizer.eurosport.com/2014/09/19/1316867-28330569-2560-1440.jpg")
stadium3 = Stadium.create!(name: "Wembley Stadium", country: "England", seats: 5, photo: "https://static.wikia.nocookie.net/footbal/images/1/13/Bag_about.jpg/revision/latest/scale-to-width-down/1440?cb=20210908173110")
stadium4 = Stadium.create!(name: "San Siro", country: "Italy", seats: 5, photo: "https://happytovisit.com/glib/3/Milan-Football-Tour-with-San-Siro-Stadium-and-Casa-Milan-1-19056.png")
stadium5 = Stadium.create!(name: "Signal Iduna Park", country: "Germany", seats: 5, photo: "https://upload.wikimedia.org/wikipedia/commons/1/13/Signal_iduna_park_stadium_dortmund_4.jpg")
stadium6 = Stadium.create!(name: "Parc des Princes", country: "France", seats: 5, photo: "https://icdn.psgtalk.com/wp-content/uploads/2019/03/Aerial-Parc-des-Princes-Paris-France-2018.jpg")
stadium7 = Stadium.create!(name: "Estadio Santiago Bernabéu", country: "Spain", seats: 5, photo: "https://images2.minutemediacdn.com/image/fetch/w_2000,h_2000,c_fit/https%3A%2F%2Ftherealchamps.com%2Fwp-content%2Fuploads%2Fgetty-images%2F2018%2F12%2F458769189.jpeg")
stadium8 = Stadium.create!(name: "Allianz Stadium", country: "Germany", seats: 5, photo: "https://upload.wikimedia.org/wikipedia/commons/thumb/0/0b/Camp_Nou_2017.jpg/1200px-Camp_Nou_2017.jpg")

team1 = Team.create!(name: "Barcelona", flag: "https://upload.wikimedia.org/wikipedia/sco/thumb/4/47/FC_Barcelona_%28crest%29.svg/1200px-FC_Barcelona_%28crest%29.svg.png")
team2 = Team.create!(name: "Bayern Munech", flag: "https://upload.wikimedia.org/wikipedia/commons/thumb/1/1f/Logo_FC_Bayern_M%C3%BCnchen_%282002%E2%80%932017%29.svg/2048px-Logo_FC_Bayern_M%C3%BCnchen_%282002%E2%80%932017%29.svg.png")
team3 = Team.create!(name: "Chelsea", flag: "https://upload.wikimedia.org/wikipedia/sco/thumb/c/cc/Chelsea_FC.svg/2048px-Chelsea_FC.svg.png")
team4 = Team.create!(name: "AC Milan", flag: "https://upload.wikimedia.org/wikipedia/commons/thumb/d/d0/Logo_of_AC_Milan.svg/1306px-Logo_of_AC_Milan.svg.png")
team5 = Team.create!(name: "Borussia Dortmund", flag: "https://upload.wikimedia.org/wikipedia/commons/thumb/6/67/Borussia_Dortmund_logo.svg/2048px-Borussia_Dortmund_logo.svg.png")
team6 = Team.create!(name: "Paris Saint-Germain", flag: "https://logos-world.net/wp-content/uploads/2020/06/PSG-Logo.png")
team7 = Team.create!(name: "Real Madrid", flag: "https://upload.wikimedia.org/wikipedia/en/thumb/5/56/Real_Madrid_CF.svg/1200px-Real_Madrid_CF.svg.png")
team8 = Team.create!(name: "Juventus", flag: "https://upload.wikimedia.org/wikipedia/commons/thumb/1/15/Juventus_FC_2017_logo.svg/640px-Juventus_FC_2017_logo.svg.png")

game1 = Game.create!(stadium: stadium1, date: "2023-06-01", available_seats: stadium1.seats)
game2 = Game.create!(stadium: stadium2, date: "2023-07-01", available_seats: stadium2.seats)
game3 = Game.create!(stadium: stadium3, date: "2023-08-01", available_seats: stadium3.seats)
game4 = Game.create!(stadium: stadium4, date: "2025-09-01", available_seats: stadium4.seats)
game5 = Game.create!(stadium: stadium4, date: "2023-09-01", available_seats: stadium4.seats)
game6 = Game.create!(stadium: stadium5, date: "2023-10-01", available_seats: stadium5.seats)
game7 = Game.create!(stadium: stadium6, date: "2023-11-01", available_seats: stadium6.seats)
game8 = Game.create!(stadium: stadium7, date: "2023-12-01", available_seats: stadium7.seats)
game9 = Game.create!(stadium: stadium1, date: "2025-01-01", available_seats: stadium1.seats)

GameTeam.create!(game: game1, team: team1)
GameTeam.create!(game: game1, team: team2)
GameTeam.create!(game: game2, team: team3)
GameTeam.create!(game: game2, team: team4)
GameTeam.create!(game: game3, team: team5)
GameTeam.create!(game: game3, team: team6)
GameTeam.create!(game: game4, team: team7)
GameTeam.create!(game: game4, team: team1)
GameTeam.create!(game: game5, team: team8)
GameTeam.create!(game: game5, team: team1)
GameTeam.create!(game: game6, team: team2)
GameTeam.create!(game: game6, team: team3)
GameTeam.create!(game: game7, team: team4)
GameTeam.create!(game: game7, team: team5)
GameTeam.create!(game: game8, team: team6)
GameTeam.create!(game: game8, team: team7)
GameTeam.create!(game: game9, team: team8)
GameTeam.create!(game: game9, team: team5)

Reservation.create!(user: user1, game: game1, reserved_seats: 1)
Reservation.create!(user: user2, game: game2, reserved_seats: 3)
Reservation.create!(user: user3, game: game3, reserved_seats: 2)
Reservation.create!(user: user1, game: game5, reserved_seats: 1)
Reservation.create!(user: user1, game: game6, reserved_seats: 2)
Reservation.create!(user: user2, game: game7, reserved_seats: 3)
Reservation.create!(user: user3, game: game8, reserved_seats: 4)
Reservation.create!(user: user1, game: game2, reserved_seats: 1)
Reservation.create!(user: user2, game: game3, reserved_seats: 2)